FROM node:20

WORKDIR /usr/src/app

RUN apt-get install -y git && \ 
    git clone https://github.com/LaserOnline/nest-js-tutorial.git && \
    apt remove -y git


WORKDIR /usr/src/app/nest-js-tutorial

RUN npm install

RUN npm run build

CMD [ "node", "dist/main.js" ]

HEALTHCHECK CMD curl --fail http://localhost:3000